export const FETCH_SLIDERS='FETCH_SLIDERS';
export const FETCH_LESSONS='FETCH_LESSONS';
export const FETCH_LESSONS_SUCCESS='FETCH_LESSONS_SUCCESS';

export const SET_SESSION_INFO='SET_SESSION_INFO';
export const FETCH_RECOMLISTS='FETCH_RECOMLISTS';
export const FETCH_PLAYLIST='FETCH_PLAYLIST';
export const FETCH_RANKINGLIST='FETCH_RANKINGLIST';
export const SETCURLOCATIONSTATE='SETCURLOCATIONSTATE';
export const SETCURSONGLIST='SETCURSONGLIST';
export const SET_COLLECTION='SET_COLLECTION';
export const SET_EXIT='SET_EXIT';